services:
  web:
    build:
      context: ./next
      dockerfile: ../Dockerfile.next
    ports:
      - "3000:3000"
    volumes:
      - ./next:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8080/
  app:
    build:
      context: ./api
      dockerfile: ../Dockerfile.api
    ports:
      - "8080:8080"
      - "2345:2345"
    command: air -c .air.toml
    volumes:
      - ./api:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=app_db
      - TZ=Australia/Sydney
      # - GIN_MODE=release for production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app_db
      - TZ=Australia/Sydney
      - PGTZ=Australia/Sydney
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

