FROM golang:1.27-alpine
WORKDIR /app
RUN go install github.com/air-verse/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.11.2
COPY go.mod go.sum* ./
RUN go mod download && go mod verify
COPY .air.toml ./
EXPOSE 8080
EXPOSE 2345
ENV GO111MODULE=on
CMD ["air", "-c", ".air.toml"]
